export const seedData = {
  categories: [
    {
      name: 'Smart Hardware',
      slug: 'smart-hardware',
      description: 'Connected sensors, telemetry nodes, and AI home automation hardware.',
      displayOrder: 1,
    },
    {
      name: 'Minimal Workspace',
      slug: 'minimal-workspace',
      description: 'Ergonomic stands, desks, and ambient lighting designed for focus.',
      displayOrder: 2,
    },
    {
      name: 'Audio Architecture',
      slug: 'audio-architecture',
      description: 'Modular acoustic drivers, high-fidelity earbuds, and noise isolation pods.',
      displayOrder: 3,
    },
    {
      name: 'Carry & Apparel',
      slug: 'carry-apparel',
      description: 'Weatherproof technical packs and minimalist daily apparel.',
      displayOrder: 4,
    },
  ],
  brands: [
    {
      name: 'MARQIVO Labs',
      slug: 'marqivo-labs',
      description: 'In-house hardware engineering and intelligent commerce design.',
    },
    {
      name: 'Aura Systems',
      slug: 'aura-systems',
      description: 'Precision environmental sensing and telemetry equipment.',
    },
    {
      name: 'Cipher Tech',
      slug: 'cipher-tech',
      description: 'Zero-trust security hardware and encrypted key managers.',
    },
  ],
  warehouses: [
    {
      name: 'Dhaka Central Hub',
      code: 'WH-DAC-01',
      address: 'Plot 14, Sector 7, Uttara',
      city: 'Dhaka',
      country: 'BD',
    },
    {
      name: 'Chittagong Port Logistics',
      code: 'WH-CTG-02',
      address: 'Agrabad Commercial Area',
      city: 'Chittagong',
      country: 'BD',
    },
  ],
  products: [
    {
      name: 'Aura Connected Sensor Node',
      slug: 'aura-connected-sensor-node',
      shortDesc: 'Automated environmental telemetry & alert engine',
      fullDesc: 'Ultra-low latency IoT sensor node capable of monitoring air quality, temperature, and motion. Features end-to-end encrypted mesh sync.',
      price: 149.0,
      compareAtPrice: 189.0,
      sku: 'MQV-SENS-101',
      stockQty: 45,
      categorySlug: 'smart-hardware',
      brandSlug: 'aura-systems',
    },
    {
      name: 'Kinetic Ergonomic Workstation Stand',
      slug: 'kinetic-ergonomic-stand',
      shortDesc: 'Precision anodized aluminum laptop & monitor elevator',
      fullDesc: 'Crafted from aerospace-grade aluminum. Provides optimal posture elevation and integrated cable management.',
      price: 129.0,
      sku: 'MQV-WORK-202',
      stockQty: 30,
      categorySlug: 'minimal-workspace',
      brandSlug: 'marqivo-labs',
    },
    {
      name: 'Pulse Modular Wireless Earbuds',
      slug: 'pulse-modular-earbuds',
      shortDesc: 'High-fidelity audio drivers with active acoustic isolation',
      fullDesc: 'Custom tuned 11mm dynamic drivers with 32-hour total playback and magnetic charging dock.',
      price: 229.0,
      compareAtPrice: 279.0,
      sku: 'MQV-AUDI-303',
      stockQty: 18,
      categorySlug: 'audio-architecture',
      brandSlug: 'marqivo-labs',
    },
    {
      name: 'Cipher Hardened Key Manager',
      slug: 'cipher-hardened-key-manager',
      shortDesc: 'Hardware security module for offline credential storage',
      fullDesc: 'Military-grade tamper-evident cryptographic key storage device supporting FIPS 140-2 security standards.',
      price: 349.0,
      sku: 'MQV-SEC-404',
      stockQty: 12,
      categorySlug: 'smart-hardware',
      brandSlug: 'cipher-tech',
    },
  ],
  customer: {
    email: 'alex.dev@marqivo.local',
    firstName: 'Alex',
    lastName: 'Rahman',
    phone: '+8801700000000',
    address: {
      recipientName: 'Alex Rahman',
      phone: '+8801700000000',
      addressLine1: 'House 42, Road 11, Banani',
      city: 'Dhaka',
      state: 'Dhaka Division',
      postalCode: '1213',
      country: 'BD',
    },
  },
};
